grafana/plugin-validator

- cmd/plugincheck/main.go
Returns a non-zero exit code on errors. Adds a `strict` flag to return a non-zero exit code on warnings. 
Fixes #6
> Fix exit code for CI builds

- pkg/plugin/check.go
- pkg/plugin/checkers.go
under windows, I successful compiled `plugincheck`
but got error
```
>plugincheck.exe ./vertamedia-clickhouse-datasource-2.2.0.zip
parse "file://C:\\Users\\Slach\\AppData\\Local\\Temp\\plugin_162473759.schema.json": invalid port ":\\Users\\Slach\\AppData\\Local\\Temp\\plugin_162473759.schema.json" after host                                                                                                         
```
during try load JSON scheme
Also,  I checked these changes under Linux via docker and Linux
```
docker run -v ./:/go/src/github.com/grafana/plugin-validator -w /go/src/github.com/grafana/plugin-validator golang:latest bash -c "go build -o plugincheck ./cmd/plugincheck/main.go && ./plugincheck ./vertamedia-clickhouse-datasource-2.2.0.zip"
```
> fix file:/// paths properly in Windows, Linux, MacOSX

- pkg/plugin/checkers.go
Hello! I have an URL to twitter.com in the plugin's README.md. Url checker gives this message:
```
$ plugincheck plugin.zip
{
"level": "error",
"message": "README contains a broken link",
"details": "Something went wrong when we tried looking up [https://twitter.com/%USERNAME%](https://twitter.com/%USERNAME%) (`400 Bad Request`)."
}
$ echo $?
1
```
There are no errors if a request has a "User-Agent" header with the "Bot" suffix.
> fix: add User-Agent to bypass scrape protection (e.g. twitter)

- cmd/plugincheck/main.go
- pkg/plugin/check.go
- pkg/plugin/checkers.go
I would like to validate a private plugin so I've added a flag to report private signature check error as warning.
Is this an acceptable solution?
> Add flag to report private signatures check error as warning

- pkg/analysis/passes/jargon/jargon.go
It can be more time-consuming to understand why the check failed if we don't know what words / phrases to look for.
> Developer Jargon: Add "disallowed" words to the failure message 

- pkg/analysis/passes/brokenlinks/brokenlinks.go
Closes https://github.com/grafana/plugin-validator/issues/46
Replaces the current user agent used for a less robot looking one
this user agents equals a linux computer using firefox 108
> Replace user agent with a "real" one

- pkg/analysis/passes/analysis.go
- pkg/analysis/passes/pluginname/pluginname.go
- pkg/analysis/passes/pluginname/pluginname_test.go
- pkg/analysis/passes/published/published.go
- pkg/analysis/passes/published/published_test.go
- pkg/analysis/passes/version/version.go
- pkg/analysis/passes/version/version_test.go
- pkg/runner/runner_test.go
- Add published version validator and replace its usage in version validator
- This validator contains the logic to see if a plugin is published and which version
- Skip human friendly names checks if the plugin is already published
Closes https://github.com/grafana/plugin-validator/issues/72
> Add Published plugin validator for later validation checks

- pkg/analysis/passes/osvscanner/osvscanner_test.go
allow tests to be skipped when osv-scanner is not in the path
> skip tests when osv-scanner cannot be found in path

- pkg/analysis/passes/legacyplatform/legacyplatform.go
- pkg/analysis/passes/legacyplatform/legacyplatform_test.go
- pkg/analysis/passes/modulejs/modulejs.go
- pkg/analysis/passes/trackingscripts/trackingscripts.go
- pkg/analysis/passes/trackingscripts/trackingscripts_test.go
- Modulejs now reports all nested modulejs files
- Tracking scripts handles nested modulejs files
- Update regex and tests for legacy platform check. 
- Legacy platform set to error if the plugin is not published.
Solves https://github.com/grafana/plugin-validator/issues/77
> Fail plugins using angularjs

- CODE_OF_CONDUCT.md
Updating the project to include a code of conduct; using the same as other Grafana projects.
> add code of conduct to project

- README.md
See https://github.com/grafana/plugin-validator/issues/71 for details.
> Provide instruction on running the plugin validator using NPX with local files.

- pkg/sourcemap/sourcemap.go
- pkg/sourcemap/sourcemap_test.go
Fixing panics by validating sourcemaps are valid. Panic example:
```
❯ ./bin/linux_amd64/plugincheck2 -config ./config/terse-json.yaml -sourceCodeUri https://github.com/TencentCloud/tencentcloud-monitor-grafana-app ~/Downloads/tencentcloud-monitor-app-2.8.2.zip           
Cloning into '/tmp/validator3743180710'...
remote: Enumerating objects: 436, done.
remote: Counting objects: 100% (436/436), done.
remote: Compressing objects: 100% (356/356), done.
remote: Total 436 (delta 149), reused 274 (delta 69), pack-reused 0
Receiving objects: 100% (436/436), 29.30 MiB | 3.88 MiB/s, done.
Resolving deltas: 100% (149/149), done.
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/grafana/plugin-validator/pkg/sourcemap.ParseSourceMapFromBytes({0xc005680000, …
```
> Fix sourcemap validation

- pkg/analysis/passes/screenshots/screenshots.go
- pkg/analysis/passes/screenshots/screenshots_test.go
Closes https://github.com/grafana/plugin-validator/issues/101
As per https://github.com/grafana/plugin-validator/issues/101#issuecomment-1473559194, return an empty array when there are no screenshots, that way `metadatapaths` will still run.
> fix: return ok when screenshots don't exist

- pkg/analysis/passes/osvscanner/osvscanner_test.go
The current OSV scanner tests are not deterministic since the library could get new reports on its database that affect the existing testdata making some tests that originally passed, fail.
While @briangann  works on the mocking mechanism to make these tests deterministic I'm skipping this test so we can release this version of the validator
> Skip flaky test

- pkg/sourcemap/sourcemap.go
Ignores svg files to check content diff. SVG files are already verified for malicious code in another check and generally webpack will reprocess them into module imports that will keep reporting false negatives
> Ignore SVG files for sourcemap diff

- pkg/sourcemap/sourcemap.go
Adds pnpm folder structure to sourcemaps validation.
Grafana toolkit has a tendency to add node_modules files from pnpm and generates false positives in the validator
> Ignores files that contain pnpm folder structure signature

- pkg/analysis/passes/trackingscripts/list.txt
Fixes https://github.com/grafana/plugin-validator/issues/105
A more technical solution could be achieved but this is a rather unused tracking domain and it is much easier to remove it from the list than account for this specifi case
> Remove po.st from banned domain list

- .github/workflows/release.yml
- .github/workflows/test.yml
Based on https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs v4 caching is enabled by default. Adding a check for the latest version in addition
> Check latest Go version when releasing

- pkg/analysis/analysis.go
- pkg/analysis/passes/analysis.go
- pkg/analysis/passes/tzap-gpt/tzap-gpt.go
- pkg/analysis/passes/tzap-gpt/tzapignore.txt
- pkg/analysis/passes/tzap-gpt/tzapinclude.txt
- pkg/cmd/plugincheck2/main.go
This PR adds support for experimental validations using openai-gpt. It uses [tzap](https://github.com/tzapio/tzap) (MIT License) to run validations against the plugin source code.
GPT models are not fully reliable in code analysis and thus a new "suspected" report category is introduced in this PR to prevent false positives to leak into a more deterministic analysis from the other analysis
> Hackaton: Experimental OpenAI-GPT code validation with tzap

- .gitignore
- pkg/analysis/passes/packagejson/packagejson.go
Fixes https://drone.grafana.net/grafana/community-pipeline/1643 when an archive is improperly structured.
```
panic: interface conversion: interface {} is nil, not []uint8
goroutine 1 [running]:
github.com/grafana/plugin-validator/pkg/analysis/passes/packagejson.run(0xc0030c1580)
/home/runner/work/plugin-validator/plugin-validator/pkg/analysis/passes/packagejson/packagejson.go:36 +0x36d
github.com/grafana/plugin-validator/pkg/runner.Check.func2(0x19dd680)
/home/runner/work/plugin-validator/plugin-validator/pkg/runner/runner.go:79 +0x1aa
github.com/grafana/plugin-validator/pkg/runner.Check.func2(0x19dd260)
/home/runner/work/plugin-validator/plugin-validator/pkg/runner/runner.go:73 +0xd8
github.com/grafana/plugin-validator/pkg/runner.Check({0x19f1c20, 0x23, 0x23}, {0xc0030b7590, 0xf}, …
```
> Fix panic when metadata is nil in packagejson analyzer

- .github/CODEOWNERS
- .github/dependabot.yml
Changes:
- Adding dependabot config
- Adding a [CODEOWNERS](https://github.com/grafana/plugin-validator/blob/02f3230f28cac9c48658761b51cdf6467b44c80e/.github/CODEOWNERS) file
> Adding dependabot to keep repo up to date
